version: "2"
stacks:
  - name: my-stack
    path: path/to/stack
hooks:
  before_plan:
    - name: "cdk-build"
      image: "public.ecr.aws/s5n0e7e5/ming-spacelift:latest"
      command: ["echo", "Hello World!"]

