AWSTemplateFormatVersion: "2010-09-09"
Capabilities:
  - CAPABILITY_IAM
Resources:
  MyLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: YourLambdaRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        # Add any additional managed policies as needed

  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: HelloWorldLambda
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Code:
        ZipFile: |
          import json

          def lambda_handler(event, context):
              print("Hello, World!")
              return {
                  'statusCode': 200,
                  'body': json.dumps('Hello from Lambda!')
              }
      Role: !GetAtt MyLambdaRole.Arn
