AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: HelloWorldLambda
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Code:
        ZipFile: |
          import json

          def lambda_handler(event, context):
              print("Hello, World!")
              return {
                  'statusCode': 200,
                  'body': json.dumps('Hello from Lambda!')
              }
